# Generated by Django 4.1 on 2022-10-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_remove_choice_votes_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="end date"
            ),
        ),
    ]
